[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Production environment settings
[context.production.environment]
  VITE_APP_ENV = "production"
  VITE_PUBLIC_SUPABASE_URL = "https://coqjcziquviehgyifhek.supabase.co"
  VITE_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvcWpjemlxdXZpZWhneWlmaGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDUzOTMsImV4cCI6MjA2NDk4MTM5M30.NSdUfHdeXLwBCcY9UO4s3LoSEBm4AuU0Jh5BLIcoQ5E"

# Staging environment settings
[context.deploy-preview.environment]
  VITE_APP_ENV = "staging"
  VITE_SUPABASE_URL = "https://your-staging-supabase-url.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-staging-anon-key"

# Branch deploy settings (for staging)
[context.branch-deploy.environment]
  VITE_APP_ENV = "staging"
  VITE_SUPABASE_URL = "https://your-staging-supabase-url.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-staging-anon-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5180
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 